apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myrelease.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "myrelease.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myrelease.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "myrelease.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ include "myrelease.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          # resources:
          #   requests:
          #     cpu: "{{ .Values.resources.requests.cpu  }}"
          #     memory: "{{ .Values.resources.requests.memory  }}"
          #   limits:
          #     cpu: "{{ .Values.resources.limits.cpu }}"
          #     memory: "{{ .Values.resources.limits.memory }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
#      volumes:
#        - name: html-volume
#          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
